include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CleanCCBGThemeSwitcher
CleanCCBGThemeSwitcher_FILES = CleanCCBGThemeSwitcher.m ../shared/CCBGMediaCatalog.m
CleanCCBGThemeSwitcher_FRAMEWORKS = UIKit AVFoundation
CleanCCBGThemeSwitcher_CFLAGS = -fobjc-arc -I../shared
CleanCCBGThemeSwitcher_INSTALL_PATH = /Library/ControlCenter/Bundles
CleanCCBGThemeSwitcher_RESOURCE_FILES = Info.plist

include $(THEOS_MAKE_PATH)/bundle.mk
