include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = CleanCCBG2x2App
CleanCCBG2x2App_FILES = CleanCCBG2x2App.m CCBGMainTabBarController.m CCBGQuickConfigController.m CCBGBackupTimelineController.m CCBGControls.m CCBGRootController.m CCBGMediaDetailController.m CCBGPreviewController.m CCBGSettingsControllers.m CCBGGenericSystemModulesController.m CCBGAdvancedControllers.m CCBGVisualFeaturesControllers.m CCBGSceneDirectorController.m CCBGSceneEditorController.m ../shared/CCBGMediaCatalog.m
CleanCCBG2x2App_FRAMEWORKS = UIKit UniformTypeIdentifiers AVFoundation QuartzCore PhotosUI Photos ImageIO QuickLookThumbnailing
CleanCCBG2x2App_CFLAGS = -fobjc-arc -I../shared
CleanCCBG2x2App_INSTALL_PATH = /Applications
CleanCCBG2x2App_RESOURCE_FILES = Info.plist AppIcon60x60@2x.png AppIcon60x60@3x.png
CleanCCBG2x2App_CODESIGN_FLAGS = -SAppEntitlements.plist

include $(THEOS_MAKE_PATH)/application.mk
