include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CleanCCBG2x2Prefs
CleanCCBG2x2Prefs_FILES = CleanCCBG2x2PrefsListController.m
CleanCCBG2x2Prefs_FRAMEWORKS = UIKit UniformTypeIdentifiers
CleanCCBG2x2Prefs_CFLAGS = -fobjc-arc
CleanCCBG2x2Prefs_LDFLAGS = -Wl,-undefined,dynamic_lookup
CleanCCBG2x2Prefs_INSTALL_PATH = /Library/PreferenceBundles
CleanCCBG2x2Prefs_RESOURCE_FILES = Info.plist Root.plist

include $(THEOS_MAKE_PATH)/bundle.mk
