#import <Foundation/Foundation.h>

@class AVAsset, UIColor, UIView;

FOUNDATION_EXPORT NSString *const CCBGPreferenceDomain;
FOUNDATION_EXPORT NSString *const CCBGReloadNotificationName;
FOUNDATION_EXPORT NSString *const CCBGSizeReloadNotificationName;
FOUNDATION_EXPORT NSString *const CCBGPresentationRecoveryNotificationName;
FOUNDATION_EXPORT NSString *const CCBGFocusRefreshNotificationName;
FOUNDATION_EXPORT NSString *const CCBGMediaDirectoryPath;

FOUNDATION_EXPORT id CCBGReadPreference(NSString *key, id fallback);
FOUNDATION_EXPORT BOOL CCBGPluginEnabled(void);
FOUNDATION_EXPORT void CCBGSetPluginEnabled(BOOL enabled);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGReadAllPreferences(void);
FOUNDATION_EXPORT void CCBGInvalidatePreferenceReadCache(void);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGConfigurationPreferencesSnapshot(void);
FOUNDATION_EXPORT void CCBGWritePreference(NSString *key, id value);
FOUNDATION_EXPORT void CCBGWritePreferences(NSDictionary<NSString *, id> *values);
FOUNDATION_EXPORT void CCBGWriteMetadataPreference(NSString *key, id value);
FOUNDATION_EXPORT void CCBGReplaceAllPreferences(NSDictionary<NSString *, id> *values);
FOUNDATION_EXPORT BOOL CCBGRestorePreferencesSnapshot(NSDictionary<NSString *, id> *values, NSError **error);
FOUNDATION_EXPORT BOOL CCBGClearAllConfigurationPreservingMedia(NSError **error);
FOUNDATION_EXPORT BOOL CCBGApplyQuickConfigurationChanges(NSDictionary<NSString *, id> *values, NSString *title);
FOUNDATION_EXPORT BOOL CCBGUndoLastQuickConfiguration(NSString **title);
FOUNDATION_EXPORT NSArray<NSDictionary<NSString *, id> *> *CCBGQuickConfigurationHistory(void);
FOUNDATION_EXPORT void CCBGClearQuickConfigurationHistory(void);
FOUNDATION_EXPORT NSArray<NSDictionary<NSString *, id> *> *CCBGVisualThemes(void);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGCaptureVisualTheme(NSString *name);
FOUNDATION_EXPORT BOOL CCBGSaveVisualTheme(NSDictionary<NSString *, id> *theme);
FOUNDATION_EXPORT BOOL CCBGApplyVisualTheme(NSString *themeID);
FOUNDATION_EXPORT BOOL CCBGApplyRandomVisualTheme(void);
FOUNDATION_EXPORT NSArray<NSDictionary<NSString *, id> *> *CCBGVisualStylePresets(void);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGCaptureVisualStylePreset(NSString *name, NSInteger slot);
FOUNDATION_EXPORT BOOL CCBGSaveVisualStylePreset(NSDictionary<NSString *, id> *preset);
FOUNDATION_EXPORT BOOL CCBGApplyVisualStylePreset(NSString *presetID, NSInteger slot);
FOUNDATION_EXPORT UIColor *CCBGResolvedDynamicPaletteColor(UIView *view, BOOL useForegroundApp, BOOL useWallpaper);
FOUNDATION_EXPORT BOOL CCBGApplyVisualThemeAutomationIfNeeded(UIView *view);
FOUNDATION_EXPORT void CCBGPostReload(void);
FOUNDATION_EXPORT void CCBGRequestControlCenterSizeReload(void);
FOUNDATION_EXPORT void CCBGPostPresentationRecovery(void);
FOUNDATION_EXPORT void CCBGRecordModuleLifecycleEvent(NSInteger slot, NSString *event, NSDictionary *details);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGReadModuleLifecycleTrace(void);
FOUNDATION_EXPORT void CCBGClearModuleLifecycleTrace(void);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGModuleDisplayNames(void);
FOUNDATION_EXPORT NSString *CCBGPreferenceKeyForModule(NSString *key, NSInteger slot);
FOUNDATION_EXPORT id CCBGReadModulePreference(NSString *key, NSInteger slot, id fallback);
FOUNDATION_EXPORT void CCBGWriteModulePreference(NSString *key, NSInteger slot, id value);
FOUNDATION_EXPORT void CCBGWriteModulePreferences(NSDictionary<NSString *, id> *values, NSInteger slot);
FOUNDATION_EXPORT NSString *CCBGActiveMediaPreferenceKey(NSInteger playbackMode);
FOUNDATION_EXPORT NSString *CCBGActiveModuleMediaName(NSInteger slot);
FOUNDATION_EXPORT void CCBGSelectModuleMedia(NSString *fileName, NSInteger slot, BOOL makeConstant);
FOUNDATION_EXPORT BOOL CCBGApplyFiveModuleDefaultMedia(void);
FOUNDATION_EXPORT BOOL CCBGRestoreFiveModuleMedia(void);
FOUNDATION_EXPORT BOOL CCBGFiveModuleDefaultsReady(void);
FOUNDATION_EXPORT NSInteger CCBGActiveModuleSlot(void);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGModuleConfigurationKeys(void);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGModuleMediaReferenceKeys(void);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGSystemMediaReferenceKeys(void);
FOUNDATION_EXPORT void CCBGCopyModuleConfiguration(NSInteger sourceSlot, NSInteger destinationSlot);
FOUNDATION_EXPORT void CCBGResetModuleConfiguration(NSInteger slot);
FOUNDATION_EXPORT void CCBGMigrateLegacyAutomationPreferences(void);
FOUNDATION_EXPORT BOOL CCBGSystemUsesDarkAppearance(void);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGDarkAppearanceDiagnostics(void);
FOUNDATION_EXPORT NSString *CCBGCurrentFocusIdentifier(void);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGCurrentFocusAliases(void);
FOUNDATION_EXPORT NSArray<NSDictionary<NSString *, id> *> *CCBGAvailableFocusModes(void);
FOUNDATION_EXPORT NSArray<NSDictionary<NSString *, id> *> *CCBGRefreshFocusModeCache(void);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGFocusDiscoveryStatus(void);
FOUNDATION_EXPORT void CCBGObserveFocusActivityChanges(void (^handler)(void));
FOUNDATION_EXPORT void CCBGInvalidateSceneRuntimeCaches(void);
FOUNDATION_EXPORT NSDictionary<NSString *, id> *CCBGSceneRuntimeContext(UIView *view);
FOUNDATION_EXPORT NSString *CCBGAutomationMediaName(NSArray<NSDictionary *> *catalog, BOOL charging, NSInteger slot);
FOUNDATION_EXPORT NSDictionary *CCBGSceneDirectorResolvedScene(NSDictionary *context);
FOUNDATION_EXPORT NSArray<NSDictionary *> *CCBGSceneDirectorMatchingScenes(NSDictionary *context);
FOUNDATION_EXPORT NSDictionary *CCBGSceneDirectorEvaluationForScene(NSDictionary *scene, NSDictionary *context);
FOUNDATION_EXPORT BOOL CCBGSceneDirectorAutomationPaused(void);
FOUNDATION_EXPORT NSString *CCBGSceneDirectorMediaForTarget(NSString *target, NSDictionary *context);
FOUNDATION_EXPORT BOOL CCBGSceneDirectorLowPowerStatic(NSDictionary *context);
FOUNDATION_EXPORT BOOL CCBGSceneDirectorBreathingGridEnabled(NSDictionary *context);
FOUNDATION_EXPORT NSInteger CCBGSceneDirectorExpandedSlot(void);
FOUNDATION_EXPORT void CCBGSceneDirectorSetExpandedSlot(NSInteger slot);
FOUNDATION_EXPORT NSString *CCBGSceneDirectorStateMediaForTarget(NSString *target, NSString *state, NSDictionary *context);
FOUNDATION_EXPORT BOOL CCBGSceneDirectorRelayFromSlotInContext(NSInteger sourceSlot, NSString *mediaName, NSDictionary *context);
FOUNDATION_EXPORT void CCBGRecordModuleRuntimeState(NSInteger slot, NSTimeInterval position, NSTimeInterval duration);
FOUNDATION_EXPORT void CCBGRecordRuntimeDiagnostic(NSString *key, id value);
FOUNDATION_EXPORT void CCBGRecordSystemOverlayPlaybackSuccess(NSString *fileName, NSString *failureKey);
FOUNDATION_EXPORT void CCBGRecordSceneTimelineEvent(NSString *event, NSDictionary *details);
FOUNDATION_EXPORT NSArray<NSDictionary *> *CCBGSceneTimeline(void);
FOUNDATION_EXPORT void CCBGReplaySceneTimelineEntry(NSDictionary *entry);
FOUNDATION_EXPORT void CCBGExitSceneTimelineReplay(void);

FOUNDATION_EXPORT BOOL CCBGIsVideoName(NSString *name);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGScanMediaNames(void);
FOUNDATION_EXPORT BOOL CCBGMediaDirectoryIsReadable(void);
FOUNDATION_EXPORT NSDictionary *CCBGDefaultMediaItem(NSString *fileName);
FOUNDATION_EXPORT NSArray<NSString *> *CCBGModuleMediaConfigurationKeys(void);
FOUNDATION_EXPORT NSDictionary *CCBGMediaItemForModule(NSDictionary *item, NSInteger slot);
FOUNDATION_EXPORT NSArray<NSDictionary *> *CCBGMediaItemsForModule(NSArray<NSDictionary *> *items, NSInteger slot);
FOUNDATION_EXPORT void CCBGSaveModuleMediaConfiguration(NSDictionary *item, NSInteger slot);
FOUNDATION_EXPORT void CCBGResetModuleMediaConfiguration(NSString *fileName, NSInteger slot);
FOUNDATION_EXPORT void CCBGRemoveMediaConfigurationFromAllModules(NSString *fileName);
FOUNDATION_EXPORT void CCBGRemoveAllMediaConfigurations(void);
FOUNDATION_EXPORT void CCBGPruneMissingMediaConfigurations(void);
FOUNDATION_EXPORT NSArray<NSDictionary *> *CCBGLoadMediaCatalog(void);
FOUNDATION_EXPORT void CCBGSaveMediaCatalog(NSArray<NSDictionary *> *catalog);
FOUNDATION_EXPORT NSDictionary *CCBGMediaItemNamed(NSArray<NSDictionary *> *catalog, NSString *fileName);
FOUNDATION_EXPORT NSString *CCBGDisplayNameForItem(NSDictionary *item);
FOUNDATION_EXPORT void CCBGLoadVideoOnlyAsset(NSString *path, void (^completion)(AVAsset *asset, NSError *error));
FOUNDATION_EXPORT void CCBGInvalidateVideoOnlyAssetMemoryCache(NSString *path);
FOUNDATION_EXPORT void CCBGInvalidateVideoOnlyAssetCache(NSString *path);
FOUNDATION_EXPORT NSString *CCBGPathForItem(NSDictionary *item);
FOUNDATION_EXPORT unsigned long long CCBGMediaStorageBytes(void);
FOUNDATION_EXPORT BOOL CCBGMediaItemIsCurrentlyEligible(NSDictionary *item);
FOUNDATION_EXPORT void CCBGRecordMediaPlaybackStart(NSString *fileName, NSInteger slot, NSTimeInterval firstFrameLatency);
FOUNDATION_EXPORT void CCBGRecordMediaPlaybackDuration(NSString *fileName, NSTimeInterval duration);
FOUNDATION_EXPORT void CCBGRecordMediaMemoryPressure(NSString *fileName);
FOUNDATION_EXPORT void CCBGRecordMediaPlaybackFailure(NSString *fileName, NSString *reason);
FOUNDATION_EXPORT void CCBGMarkMediaFailure(NSString *fileName, NSString *reason);
FOUNDATION_EXPORT void CCBGClearMediaFailure(NSString *fileName);
FOUNDATION_EXPORT NSString *CCBGSHA256ForFileAtPath(NSString *path);
FOUNDATION_EXPORT NSString *CCBGDominantColorHexForImageAtPath(NSString *path);
FOUNDATION_EXPORT NSString *CCBGDominantColorHexForMediaAtPath(NSString *path);
FOUNDATION_EXPORT void CCBGReplaceMediaReferences(NSString *oldName, NSString *newName);
