include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CleanCCBGMasterSwitch
CleanCCBGMasterSwitch_FILES = CleanCCBGMasterSwitch.m ../shared/CCBGMediaCatalog.m
CleanCCBGMasterSwitch_FRAMEWORKS = UIKit
CleanCCBGMasterSwitch_CFLAGS = -fobjc-arc -I../shared
CleanCCBGMasterSwitch_INSTALL_PATH = /Library/ControlCenter/Bundles
CleanCCBGMasterSwitch_RESOURCE_FILES = Info.plist

include $(THEOS_MAKE_PATH)/bundle.mk
