include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CleanCCBGDefaultRestore
CleanCCBGDefaultRestore_FILES = CleanCCBGDefaultRestore.m ../shared/CCBGMediaCatalog.m
CleanCCBGDefaultRestore_FRAMEWORKS = UIKit
CleanCCBGDefaultRestore_CFLAGS = -fobjc-arc -I../shared
CleanCCBGDefaultRestore_INSTALL_PATH = /Library/ControlCenter/Bundles
CleanCCBGDefaultRestore_RESOURCE_FILES = Info.plist

include $(THEOS_MAKE_PATH)/bundle.mk
